# ------------------> Development Image
FROM node:18.12.1-bullseye-slim
ENV NODE_ENV=production
WORKDIR /usr/src/app
COPY ./package*.json .
RUN npm install --only=production
COPY . . 
CMD ["npm", "run", "start"]